Header header

geometry_msgs/Quaternion orientation
float64[9] orientation_covariance # Row major about x, y, z axes
geometry_msgs/Point position
float64[9] position_covariance # Row major about x, y, z axes
geometry_msgs/Quaternion q_GtoI
geometry_msgs/Vector3 ba # Accelerometer Bias
geometry_msgs/Vector3 bg # Gyroscope Bias 
geometry_msgs/Vector3 v_IinG # Imu speed in Global frame
geometry_msgs/Vector3 gravity # Gravity value in local frame
